version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "npm"
      - "automated"
      - "maintenance"
    assignees:
      - "Hydradevx"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 20
    labels:
      - "ci"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    assignees:
      - "Hydradevx"
    rebase-strategy: "disabled"
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "UTC"
    labels:
      - "docker"
      - "dependencies"
    assignees:
      - "Hydradevx"
    commit-message:
      prefix: "docker(deps)"
      include: "scope"
    rebase-strategy: "auto"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "UTC"
    labels:
      - "rust"
      - "dependencies"
    assignees:
      - "Hydradevx"
    commit-message:
      prefix: "cargo(deps)"
      include: "scope"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "all"
